"""empty message

Revision ID: 08a7ebcc6ce2
Revises: 5b405ae134bd
Create Date: 2020-10-27 16:49:49.083427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a7ebcc6ce2'
down_revision = '5b405ae134bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
