"""empty message

Revision ID: 20ae2dd21fda
Revises: 437c584563f6
Create Date: 2020-11-03 15:02:11.345271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ae2dd21fda'
down_revision = '437c584563f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('request_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'request_status')
    # ### end Alembic commands ###
