"""empty message

Revision ID: 221c78078fa5
Revises: 08a7ebcc6ce2
Create Date: 2020-10-27 16:50:07.593395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221c78078fa5'
down_revision = '08a7ebcc6ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
