"""empty message

Revision ID: 3b6e92b76a40
Revises: cebfec850b9d
Create Date: 2020-11-10 09:54:41.761274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6e92b76a40'
down_revision = 'cebfec850b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('price', sa.Float(), nullable=False))
    op.create_unique_constraint('unique_u_r', 'reservation', ['user_id', 'arrangement_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_u_r', 'reservation', type_='unique')
    op.drop_column('reservation', 'price')
    # ### end Alembic commands ###
