"""empty message

Revision ID: 437c584563f6
Revises: af1d03f63903
Create Date: 2020-11-02 11:29:03.531941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437c584563f6'
down_revision = 'af1d03f63903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('arrangement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
