"""empty message

Revision ID: 5b405ae134bd
Revises: 96fc6066b690
Create Date: 2020-10-27 16:46:49.903826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b405ae134bd'
down_revision = '96fc6066b690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
