"""empty message

Revision ID: 939ef590e6e5
Revises: 6756503cc44c
Create Date: 2020-10-29 13:05:14.280635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939ef590e6e5'
down_revision = '6756503cc44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('arrangement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
