"""empty message

Revision ID: 96fc6066b690
Revises: c2d2b37ddf2b
Create Date: 2020-10-27 16:42:48.785483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fc6066b690'
down_revision = 'c2d2b37ddf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
