"""empty message

Revision ID: a74769994655
Revises: 939ef590e6e5
Create Date: 2020-10-29 13:54:51.798629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74769994655'
down_revision = '939ef590e6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservations_arrangement_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'arrangement', ['arrangement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_arrangement_id_fkey', 'reservations', 'arrangement', ['arrangement_id'], ['id'])
    # ### end Alembic commands ###
