"""empty message

Revision ID: af1d03f63903
Revises: a74769994655
Create Date: 2020-11-02 10:12:24.581147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1d03f63903'
down_revision = 'a74769994655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangement', sa.Column('travel_guide_id', sa.Integer(), nullable=True))
    op.drop_constraint('arrangement_tourist_guide_id_fkey', 'arrangement', type_='foreignkey')
    op.create_foreign_key(None, 'arrangement', 'user', ['travel_guide_id'], ['id'])
    op.drop_column('arrangement', 'tourist_guide_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangement', sa.Column('tourist_guide_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'arrangement', type_='foreignkey')
    op.create_foreign_key('arrangement_tourist_guide_id_fkey', 'arrangement', 'user', ['tourist_guide_id'], ['id'])
    op.drop_column('arrangement', 'travel_guide_id')
    # ### end Alembic commands ###
