"""empty message

Revision ID: cebfec850b9d
Revises: 653642bbe828
Create Date: 2020-11-09 17:40:17.674979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebfec850b9d'
down_revision = '653642bbe828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('arrangement_id', sa.Integer(), nullable=False),
    sa.Column('num_of_places', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('implementation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implementation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('arrangement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('num_of_places', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangement.id'], name='implementation_arrangement_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='implementation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='implementation_pkey'),
    sa.UniqueConstraint('user_id', 'arrangement_id', name='unique_u_r')
    )
    op.drop_table('reservation')
    # ### end Alembic commands ###
