"""empty message

Revision ID: cf883aee8e05
Revises: 6756503cc44c
Create Date: 2020-11-09 09:36:56.576913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf883aee8e05'
down_revision = '6756503cc44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangement', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('arrangement', sa.Column('travel_guide_id', sa.Integer(), nullable=True))
    op.drop_constraint('arrangement_tourist_guide_id_fkey', 'arrangement', type_='foreignkey')
    op.create_foreign_key(None, 'arrangement', 'user', ['travel_guide_id'], ['id'])
    op.drop_column('arrangement', 'tourist_guide_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangement', sa.Column('tourist_guide_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'arrangement', type_='foreignkey')
    op.create_foreign_key('arrangement_tourist_guide_id_fkey', 'arrangement', 'user', ['tourist_guide_id'], ['id'])
    op.drop_column('arrangement', 'travel_guide_id')
    op.drop_column('arrangement', 'is_active')
    # ### end Alembic commands ###
